# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: [ main ]

jobs:


  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: semantic-versioning-tag
        uses: LongOddCode/semantic-versioning-tag@0.6.0
        id: svt

      - name: validation and set params
        run: |
          echo ${{ steps.svt.outputs.major }}
          echo ${{ steps.svt.outputs.minor }}
          echo ${{ steps.svt.outputs.patch }}
          echo ${{ steps.svt.outputs.prerelease }}
          echo ${{ steps.svt.outputs.buildmetadata }}

      #Create Release
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false


